version: '3.0.0'
services:
  db:
    container_name: db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api

