server:
  port: 8888

spring:
  application:
    name: app.test.containers

  datasource:
    url: jdbc:postgresql://localhost:5432/api
    username: api
    password: api

  jpa:
    show-sql: true

flyway:
  user: api
  password: api